In [1]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

/Users/cinar/.pyenv/versions/3.13.14/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
documents = [
    "JWT token'ları modern API'lerde kimlik doğrulama için kullanılır.",
    "OAuth2 üçüncü parti uygulamalar için yetkilendirme sağlar.",
    "JWT token'ları local storage veya cookie içinde saklanabilir.",
    "OAuth2 authorization code ve client credentials akışlarını destekler.",
    "Authentication kullanıcıyı doğrular, authorization ise kullanıcının yetkilerini belirler."
]

In [3]:
model=SentenceTransformer("all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6144.93it/s]


In [4]:
model

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [5]:
doc_embeddings=model.encode(documents)

In [6]:
doc_embeddings

array([[-1.03138804e-01,  3.94771397e-02, -3.93518421e-05, ...,
         4.27323170e-02,  4.53937203e-02, -3.31611298e-02],
       [-5.92900105e-02,  1.33441553e-01, -7.61116147e-02, ...,
         6.35225251e-02,  8.75766575e-03, -1.83341894e-02],
       [-4.35138196e-02,  4.22054157e-02, -5.75083233e-02, ...,
         4.25524861e-02, -1.87670160e-02, -6.05263598e-02],
       [-6.18409216e-02,  8.07105601e-02, -8.51756260e-02, ...,
         1.05832152e-01,  3.91424298e-02, -6.55529499e-02],
       [-9.87699926e-02,  7.07390904e-02, -4.62277308e-02, ...,
         6.03449531e-02,  5.45622706e-02, -3.19804903e-03]],
      shape=(5, 384), dtype=float32)

In [7]:
query="JWT autehntıcation nasıl çalışır"

In [8]:
query_embedding=model.encode(query)

In [9]:
query_embedding

array([-1.52442371e-02,  3.42674404e-02,  7.93965813e-03,  2.16986034e-02,
       -8.01644772e-02, -2.06307098e-02,  1.05115876e-01, -1.10707879e-02,
        5.10653928e-02, -5.04716113e-02,  2.49474365e-02,  3.07659488e-02,
       -7.87741097e-04, -1.83612835e-02,  7.24287406e-02, -5.28664663e-02,
       -8.79075900e-02,  1.10478528e-01, -8.97665694e-02, -1.14872545e-01,
       -1.81697868e-03,  2.59296540e-02,  5.17023914e-03, -2.25128792e-02,
        1.01259304e-02, -7.08016008e-02,  5.45066744e-02, -4.12051976e-02,
       -9.55511292e-04,  4.37484570e-02,  4.97300625e-02,  8.59943312e-03,
        9.74941161e-03, -8.44863337e-03, -6.00410737e-02,  6.52993247e-02,
       -7.51133934e-02, -3.71808074e-02,  9.07613188e-02, -5.87507337e-02,
       -3.59717943e-02, -1.36211917e-01, -2.95684095e-02, -6.82303682e-02,
        1.50471518e-03,  2.84623485e-02, -6.68328851e-02,  1.94566287e-02,
       -3.08383591e-02,  1.17279030e-02, -7.74321035e-02, -5.43059446e-02,
        3.82253854e-03, -

In [10]:
scores=np.dot(doc_embeddings,query_embedding.T).flatten()

In [11]:
best_index=np.argmax(scores)

In [12]:
query

'JWT autehntıcation nasıl çalışır'

In [13]:
documents[best_index]

"JWT token'ları modern API'lerde kimlik doğrulama için kullanılır."

In [14]:
bad_chunks = [
    "JWT token'ları kullanılır.",
    "OAuth2 yetkilendirme sağlar.",
    "Authentication ve authorization farklıdır.",
    "Token'lar cookie içinde tutulabilir."
]

In [15]:
chunk_embeddings=model.encode(bad_chunks)

In [16]:
scores=np.dot(chunk_embeddings,query_embedding.T).flatten()
chunk_index=np.argmax(scores)

In [17]:
bad_chunks[chunk_index]

"JWT token'ları kullanılır."

In [18]:
query

'JWT autehntıcation nasıl çalışır'

In [19]:
semantic_scores=np.dot(doc_embeddings,query_embedding.T).flatten()

In [20]:
semantic_scores

array([0.6803909 , 0.4724997 , 0.5876236 , 0.40856135, 0.5279442 ],
      dtype=float32)

In [21]:
semantic_index=np.argmax(semantic_scores)

In [22]:
documents[semantic_index]

"JWT token'ları modern API'lerde kimlik doğrulama için kullanılır."

In [23]:
vectorizer=TfidfVectorizer()

In [24]:
tfidf_matrix=vectorizer.fit_transform(documents)

In [25]:
query_matrix=vectorizer.transform([query])

In [26]:
keyword_scores=np.dot(tfidf_matrix.toarray(),query_matrix.toarray().T).flatten()

In [27]:
keyword_index=np.argmax(keyword_scores)

In [28]:
documents[keyword_index]

"JWT token'ları local storage veya cookie içinde saklanabilir."

In [29]:
context=documents[semantic_index]

In [30]:
context

"JWT token'ları modern API'lerde kimlik doğrulama için kullanılır."

In [32]:
from dotenv import load_dotenv
from openai import OpenAI
import os

In [33]:
load_dotenv()

True

In [34]:
client=OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [35]:
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {
            "role": "system",
            "content": "Sadece verilen context'e göre cevap ver."
        },
        {
            "role": "user",
            "content": f"""
Context:
{context}

Soru:
{query}
"""
        }
    ]
)

In [37]:
response.choices[0].message.content

'JWT (JSON Web Token) kimlik doğrulaması, aşağıdaki adımlarla çalışır:\n\n1. **Kullanıcı Girişi**: Kullanıcı, kimlik bilgileri (örneğin, kullanıcı adı ve şifre) ile giriş yapar.\n  \n2. **Token Oluşturma**: Sunucu, kullanıcının kimliğini doğruladıktan sonra, kullanıcının bilgilerini içeren bir JWT oluşturur. Bu token, genellikle üç bölümden oluşur: header, payload ve signature.\n\n3. **Token Gönderimi**: Sunucu, oluşturulan JWT\'yi istemciye gönderir. İstemci, bu token\'ı genellikle tarayıcının yerel depolama alanında saklar.\n\n4. **İsteklerde Kullanım**: Kullanıcı, korunan bir kaynak talep ettiğinde (örneğin, bir API isteği), istemci bu JWT\'yi istekle birlikte sunucuya gönderir. Bu genellikle HTTP başlıklarında "Authorization" başlığı altında yapılır.\n\n5. **Token Doğrulama**: Sunucu, gelen JWT\'yi alır ve imzasını doğrular. Eğer token geçerli ise (örneğin, süresi dolmamışsa ve imzası doğruysa), kullanıcı kimliği doğrulanır ve istenen kaynak sağlanır.\n\n6. **Erişim Kontrolü**: Sun